<!-- application/layouts/scripts/layout.phtml -->
    <?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle(); ?> 
        <style>
            #container {
                width: 950px;
            }
            .items {
                float: left;
                width: 750px;
            }
            .view {
                border: 1px solid #C9E0ED;
                margin: 10px 0;
                padding: 10px;
            }
            .sidebar {
                border: 1px solid #C9E0ED;
                margin-right: 0;
                width: 190px;
                height: 200px;
                float: left;
            }
        </style>
      <?php //echo $this->headLink()->appendStylesheet('/css/global.css') ?>
    </head>
    <body>
        <div id="container">
            <h1><?php echo $this->escape($this->title); ?></h1>
            <?php echo $this->layout()->content ?> 
            <div class='sidebar'>sidebar</div>
        </div>
    </body>
    </html>